### PR TITLE
Enclosed quotes expansion

### PR DESCRIPTION
**Pull request by mguinness**
Text with quotes is escaped but not enclosed with quotes per [RFC4180](https://tools.ietf.org/html/rfc4180):

> If fields are not enclosed with double quotes, then double quotes may not appear inside the fields.

For example `Reviewed "bad" code` is output as `Reviewed ""bad"" code` instead of `"Reviewed ""bad"" code"`.

Another possible change not included in this PR is preserving new line characters by enclosing with double quotes:

> Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.

That would be a breaking change, but another formatter option could be added for backwards compatibility.

### CODE REVIEW

**Comment by mguinness** [comment]
Thought I'd follow up, will anyone be able to review?

**Comment by damienbod** [comment]
@mguinness I'll review this at the weekend, next week. Sorry about missing this. Could you fix the fix merge conflict in the meantime

Greetings Damien

**Review by damienbod — APPROVED** [review]

**Comment by damienbod** [comment]
@mguinness  works great, thanks

**Comment by damienbod** [comment]
released : https://www.nuget.org/packages/WebApiContrib.Core.Formatter.Csv/4.0.0

**Pull request merged**
