### PR TITLE
updating to msbuild

### PR DESCRIPTION
**Pull request by damienbod**

### CODE REVIEW

**Comment by damienbod** [comment]
@filipw

**Comment by damienbod** [comment]
@filipw The VS2017 RC image is private and you need to request that the user used for this build is added in this issue:
https://github.com/appveyor/ci/issues/1179#issuecomment-264055820

**Comment by damienbod** [comment]
@filipw Can we merge build and tests run.

**Comment by filipw** [comment]
thanks

**Comment by khellang** [comment]
Aww, man. Now I can't even open these projects anymore 😢

**Comment by damienbod** [comment]
@khellang sorry ... Have you installed VS2017 RC?

**Pull request merged**
