### PR TITLE
updated WebApiContrib.Core.Formatter.Protobuf to latest protobuf-net …

### LINKED ISSUE #209: TypeModel.Create is obsolete with latest protobuf-net (3.0.29)
Hi,

I started to get runtime errors after updating to the latest protobuf-net version. After compiling your code locally I see that the TypeModel.Create() method has been marked as obsolete and needs to be replaced with RuntimeTypeModel.Create().

After I replaced it in the ProtobufInputFormatter.cs and ProtobufOutputFormatter.cs, it is working correctly.

### PR DESCRIPTION
**Pull request by filipw**
…and created a netcoreapp3.1 target

fixes #209

### CODE REVIEW

**Comment by damienbod** [comment]
Will do some manuel testing and create a package, hopefully at the weekend.

**Comment by devindran** [comment]
Hello, hoping to see a package for this soon.

**Comment by damienbod** [comment]
@devindran sorry forgot about this, will do this tomorrow.

Greetings Damien

**Comment by damienbod** [comment]
Released

https://www.nuget.org/packages/WebApiContrib.Core.Formatter.Protobuf/3.0.0/

Thankd for the PR!

**Pull request merged**
