### PR TITLE
Damienbod netstandard2

### PR DESCRIPTION
**Pull request by damienbod**
WebApiContrib.Core.Protobuf
WebApiContrib.Core.Formatter.Csv

Only supporting dotnet 2.0 now,

I'll update the others if this is ok

### CODE REVIEW

**Comment by damienbod** [comment]
Also updated to dotnet 2.0
WebApiContrib.Core.Formatter.MessagePack
WebApiContrib.Core.Formatter.PlainText

**Comment by damienbod** [comment]
Also WebApiContrib.Core.Formatter.Yaml

**Comment by filipw** [comment]
while you are at it, can you update all of them? 😆

**Comment by damienbod** [comment]
@filipw Could you merge this as it is? I'll do then BSON and the versioning in separate branches then, and after that the rest. 

Greetings Damien

**Comment by damienbod** [comment]
@filipw Once I finished, we need to create new npm packages for the new versions

**Comment by filipw** [comment]
thanks

**Pull request merged**
